name: Measure coverage

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'adopt'
        architecture: x64
        cache: maven
    - name: maven setup
      uses: stCarolas/setup-maven@v4.2
      with:
        maven-version: 3.5.2
    - name: build & test
      run: mvn package -B

    - name: Jacoco Report to PR
      id: jacoco
      uses: madrapps/jacoco-report@v1.2
      with:
        path: ${{ github.workspace }}/target/site/jacoco/jacoco.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        min-coverage-overall: 40
        min-coverage-changed-files: 60
        debug-mode: false

    - name: Get the Coverage info
      run: |
        echo "Total coverage ${{ steps.jacoco.outputs.coverage-overall }}"
        echo "Changed Files coverage ${{ steps.jacoco.outputs.coverage-changed-files }}"
